import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./global.css";

import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Daniel Peñaloza | Developer Portfolio",
	description: "Generated by create next app",
	icons: {
		icon: "/icon.svg",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				id="layout"
				className={`${inter.className} ${montserrat.className} bg-white`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
